# Numpy part 1 

In [ ]:
## it is bascially used to perform operations based oon array and matrixes

In [2]:
import numpy as np

In [1]:
l = [1,2,3,4,5,6]

In [5]:
arr =np.array(l)  ### here we are trying to convert a list into an array

In [18]:
type(arr)  ## ndarray means n dimensional array

numpy.ndarray

In [9]:
np.asarray(l) # in this way we can also convert a list into an array

array([1, 2, 3, 4, 5, 6])

In [11]:
arr1 = np.array([[1,2,3],[4,5,6]])

In [15]:
arr.ndim  ### ndim is used to check dimention of the array

1

In [16]:
arr1.ndim

2

In [19]:
arr1

array([[1, 2, 3],
       [4, 5, 6]])

In [26]:
mat = np.matrix(l) ## here we are converting list into matrix  In a matrix minimum dimension is 2 
mat

matrix([[1, 2, 3, 4, 5, 6]])

In [24]:
np.asanyarray(l)  ### here as we see list is converting into array

array([1, 2, 3, 4, 5, 6])

In [27]:
np.asanyarray(mat)  ## we can see here nothing is changed beacuse in a numpy matrix is a sub class of array

matrix([[1, 2, 3, 4, 5, 6]])

In [35]:
a = arr  ### here it will try to take a referance of arr , it will not makeing a copy of array

In [28]:
arr

array([1, 2, 3, 4, 5, 6])

In [30]:
a

array([1, 2, 3, 4, 5, 6])

In [48]:
### as we know 'a' is a reference of arr thats why if we make any kind of change in any of them it will change for both  
## here the memory loction is same for both  this type of copy is called solo copy 
a[0]=100

In [33]:
arr

array([100,   2,   3,   4,   5,   6])

In [34]:
a

array([100,   2,   3,   4,   5,   6])

In [47]:
 ## here we are copying the arr  so if we will perform any change in any of them then it will not affect to other ones
###here the memory location is different for both  this type of copy is called deep copy 
b =np.copy(arr)

In [42]:
b[0]=253

In [43]:
b

array([253,   2,   3,   4,   5,   6])

In [44]:
arr

array([100,   2,   3,   4,   5,   6])

In [52]:
## here we are trying to create a array using function 
# We are passing a size of array i.e 3*3 and a condition using lambda fun 
## as we know array is made by x and y axis so in this case it will take i in x axis and j in y axis 
## as the shape of array is 3*3 so it will take 3 same values for both i and j i.e. i=0,1,2 and j=0,1,2 
## as the i and j is ploted on axis it will check given condition at each intersection of i and j 
np.fromfunction(lambda i,j : i==j, (3,3))  

array([[ True, False, False],
       [False,  True, False],
       [False, False,  True]])

In [51]:
np.fromfunction(lambda i,j : i*j, (3,3))

array([[0., 0., 0.],
       [0., 1., 2.],
       [0., 2., 4.]])

In [54]:
list(i*i for i in range(5))  ## as the range is 5 it will assign values of i = 0,1,2,3,4

[0, 1, 4, 9, 16]

In [67]:
iterable = (i*i for i in range(5)) ## we are trying to perfrom above operation using np  Here this statment gives us a data set

In [68]:
np.fromiter(iterable,float)  ### here we are creating an array using data set

array([ 0.,  1.,  4.,  9., 16.])

In [69]:
## here we are creating an array from a string 
## while perfroming this type of operation we always need to give a seprator denoted by 'sep'
np.fromstring("23 25 63", sep = " ") 

array([23., 25., 63.])

In [70]:
np.fromstring("23,25,63", sep = ",")

array([23., 25., 63.])

In [71]:
arr

array([100,   2,   3,   4,   5,   6])

In [72]:
arr1

array([[1, 2, 3],
       [4, 5, 6]])

In [73]:
arr.ndim

1

In [74]:
arr1.ndim

2

In [75]:
arr.size  ## it shows the total elements present inside a array

6

In [76]:
arr1.size

6

In [79]:
arr.shape  ### it tells about the shape of array in this case it is 6*1

(6,)

In [80]:
arr1.shape

(2, 3)

In [81]:
arr.dtype

dtype('int64')

In [82]:
arr1.dtype

dtype('int64')

# Numpy part 2 

In [11]:
import numpy as np

In [2]:
list(range(5))

[0, 1, 2, 3, 4]

In [3]:
list(range(0,10))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [5]:
list(range(0.4,0.10))  # range does not allow the float

TypeError: 'float' object cannot be interpreted as an integer

In [17]:
list(np.arange(0.4 , 10.4,0.23))  # this is similar to range function the only difference is it can take fraction as well

[0.4,
 0.63,
 0.86,
 1.0899999999999999,
 1.3199999999999998,
 1.5499999999999998,
 1.7799999999999998,
 2.01,
 2.2399999999999998,
 2.4699999999999998,
 2.6999999999999997,
 2.9299999999999997,
 3.1599999999999997,
 3.3899999999999997,
 3.6199999999999997,
 3.8499999999999996,
 4.08,
 4.31,
 4.54,
 4.77,
 5.0,
 5.23,
 5.46,
 5.6899999999999995,
 5.92,
 6.15,
 6.38,
 6.609999999999999,
 6.84,
 7.07,
 7.3,
 7.529999999999999,
 7.76,
 7.99,
 8.219999999999999,
 8.45,
 8.68,
 8.91,
 9.139999999999999,
 9.37,
 9.6,
 9.83,
 10.06,
 10.29]

In [25]:
np.linspace(1,10,5)  ## linspace function create an array by dividing a given range into equal given steps 

array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ])

In [28]:
#logspace function create an array by dividing a given range into equal given steps and give a logarithmic value with given base
np.logspace(1,5, 10 ,base=2) 

array([ 2.        ,  2.72158   ,  3.70349885,  5.0396842 ,  6.85795186,
        9.33223232, 12.69920842, 17.28095582, 23.51575188, 32.        ])

In [30]:
np.zeros(5) # it will genrate an array of given shape with cantaining all zeros

array([0., 0., 0., 0., 0.])

In [31]:
np.zeros((5,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [32]:
np.zeros((3,4,2)) ## it will create an array with 3 matrixes each having dimension 4*2

array([[[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]]])

In [34]:
# we can generate as many as possible arrays but we can visualization only upto 3D array
# in this case 2 sets of 4*1 matrixes are created like that 3 sets will created
np.zeros((3,2,4,1))  

array([[[[0.],
         [0.],
         [0.],
         [0.]],

        [[0.],
         [0.],
         [0.],
         [0.]]],


       [[[0.],
         [0.],
         [0.],
         [0.]],

        [[0.],
         [0.],
         [0.],
         [0.]]],


       [[[0.],
         [0.],
         [0.],
         [0.]],

        [[0.],
         [0.],
         [0.],
         [0.]]]])

In [35]:
np.ones(5) ### it will create matrix cantaining 1

array([1., 1., 1., 1., 1.])

In [38]:
arr = np.ones((5,4))

In [39]:
arr


array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [40]:
arr + 5 ## it will add 5 in every element 

array([[6., 6., 6., 6.],
       [6., 6., 6., 6.],
       [6., 6., 6., 6.],
       [6., 6., 6., 6.],
       [6., 6., 6., 6.]])

In [41]:
arr*5

array([[5., 5., 5., 5.],
       [5., 5., 5., 5.],
       [5., 5., 5., 5.],
       [5., 5., 5., 5.],
       [5., 5., 5., 5.]])

When you call numpy.empty() to create a new array, it allocates a block of memory with the requested size and shape, but it doesn't initialize the values of the array. The content of the array will be whatever happens to be in that memory at the time, which is typically unpredictable and dependent on a number of factors, such as the state of the computer's memory and what other programs are running at the time.

In [47]:
np.empty((3,4))

array([[6.94634885e-310, 0.00000000e+000, 1.01855798e-312,
        9.54898106e-313],
       [1.16709769e-312, 1.03977794e-312, 1.23075756e-312,
        1.06099790e-312],
       [1.03977794e-312, 9.76118064e-313, 1.06099790e-312,
        1.90979621e-312]])

In [50]:
arr1 =np.eye(5) ## it always gives us a identical matixes as we know identical matrixes are always a square matrixes

In [51]:
import pandas as pd 

In [52]:
pd.DataFrame(arr1)  ## we can convert an array into an data frame 

0    1    2    3    4
0  1.0  0.0  0.0  0.0  0.0
1  0.0  1.0  0.0  0.0  0.0
2  0.0  0.0  1.0  0.0  0.0
3  0.0  0.0  0.0  1.0  0.0
4  0.0  0.0  0.0  0.0  1.0

In [53]:
np.random.rand(2,3) ## it will genrate a random data 

array([[0.3825463 , 0.10742205, 0.13695681],
       [0.20859054, 0.93787227, 0.23359193]])

In [55]:
np.random.randn(2,3)  ## it randn the mean of data is zero and the maximum standard deviation is 1 

array([[-0.01523046, -0.48319584, -0.49302121],
       [-0.85934505,  0.77186562,  1.045942  ]])

In [59]:
arr2 = np.random.randint(1,5,(3,4)) ## it will create a matrix of 3*4 where all the elements is in range of 1 to 5

In [61]:
arr2

array([[4, 4, 2, 2],
       [4, 2, 1, 1],
       [4, 2, 3, 4]])

In [60]:
arr2.size

12

In [62]:
arr2.shape

(3, 4)

In [65]:
arr2.reshape(2,6) ## while using reshape function size of an array can not be changed and elements are also not going to changee

array([[4, 4, 2, 2, 4, 2],
       [1, 1, 4, 2, 3, 4]])

In [66]:
arr2.reshape(3,6)

ValueError: cannot reshape array of size 12 into shape (3,6)

In [68]:
arr2.reshape(3,-5201256) ## while using reshape fun if we assigned a any one negative value then it will automactially understands the remaining value

array([[4, 4, 2, 2],
       [4, 2, 1, 1],
       [4, 2, 3, 4]])

In [73]:
arr2.reshape(3,-5201256,1,1,1,1)

array([[[[[[4]]]],



        [[[[4]]]],



        [[[[2]]]],



        [[[[2]]]]],




       [[[[[4]]]],



        [[[[2]]]],



        [[[[1]]]],



        [[[[1]]]]],




       [[[[[4]]]],



        [[[[2]]]],



        [[[[3]]]],



        [[[[4]]]]]])

In [75]:
arr3 = np.random.randint(1,10 ,(5,6))

In [76]:
arr3

array([[1, 4, 8, 7, 9, 3],
       [2, 8, 2, 9, 6, 7],
       [8, 1, 6, 2, 1, 5],
       [7, 6, 4, 8, 3, 3],
       [7, 7, 9, 3, 9, 7]])

In [79]:
arr3 > 8 ## we can find the data inside an array based on our conditions

array([[False, False, False, False,  True, False],
       [False, False, False,  True, False, False],
       [False, False, False, False, False, False],
       [False, False, False, False, False, False],
       [False, False,  True, False,  True, False]])

In [78]:
arr3[arr3>8]

array([9, 9, 9, 9])

In [80]:
arr3

array([[1, 4, 8, 7, 9, 3],
       [2, 8, 2, 9, 6, 7],
       [8, 1, 6, 2, 1, 5],
       [7, 6, 4, 8, 3, 3],
       [7, 7, 9, 3, 9, 7]])

In [81]:
arr3[0]

array([1, 4, 8, 7, 9, 3])

In [86]:
arr3[0,[1,3,2,4]] ## we can extract data what ever we want 

array([4, 7, 8, 9])

In [88]:
arr3[2:4,[2,3]]

array([[6, 2],
       [4, 8]])

In [89]:
arr4 = np.random.randint(1,3,(3,3))
arr5 = np.random.randint(1,3,(3,3))

In [90]:
arr4

array([[2, 1, 1],
       [2, 1, 1],
       [1, 1, 1]])

In [92]:
arr5

array([[1, 1, 1],
       [1, 2, 2],
       [1, 1, 2]])

In [94]:
arr4+arr5 ## it is performing addision index wise

array([[3, 2, 2],
       [3, 3, 3],
       [2, 2, 3]])

In [95]:
arr4-arr5

array([[ 1,  0,  0],
       [ 1, -1, -1],
       [ 0,  0, -1]])

In [96]:
arr4*arr5 ## it is not a matrix multiplication it is just performing index wise multiplication

array([[2, 1, 1],
       [2, 2, 2],
       [1, 1, 2]])

In [97]:
# if we want to take matrix multipication 
arr4@arr5 ## @ symbol is used to do matrix multiplication

array([[4, 5, 6],
       [4, 5, 6],
       [3, 4, 5]])

In [98]:
arr4/arr5 # it will perform indexwise division

array([[2. , 1. , 1. ],
       [2. , 0.5, 0.5],
       [1. , 1. , 0.5]])

In [101]:
arr4/0 ## by dividing zero it will give infinity

/tmp/ipykernel_105/2627289438.py:1: RuntimeWarning: divide by zero encountered in divide
  arr4/0 ## by dividing zero it will give infinity


array([[inf, inf, inf],
       [inf, inf, inf],
       [inf, inf, inf]])

In [102]:
# Numpy - Broadcasting

In [103]:
arr6=np.zeros((3,4))

In [104]:
arr6

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [105]:
arr6 + 5

array([[5., 5., 5., 5.],
       [5., 5., 5., 5.],
       [5., 5., 5., 5.]])

In [113]:
a = np.array([1,2,3,4])

In [114]:
arr6+ a ## it will add column wise

array([[1., 2., 3., 4.],
       [1., 2., 3., 4.],
       [1., 2., 3., 4.]])

In [117]:
b = np.array([[3,4,5]])

In [118]:
arr6+b ## to remove this error we need to rotate an array. To rotate an array, array must be having 2 dimensional

ValueError: operands could not be broadcast together with shapes (3,4) (1,3) 

In [122]:
 arr7 =arr6+b.T

In [123]:
arr7

array([[3., 3., 3., 3.],
       [4., 4., 4., 4.],
       [5., 5., 5., 5.]])

In [121]:
b.T

array([[3],
       [4],
       [5]])

In [125]:
np.sqrt(arr7)  ## we can find out square root of each elemnt in array

array([[1.73205081, 1.73205081, 1.73205081, 1.73205081],
       [2.        , 2.        , 2.        , 2.        ],
       [2.23606798, 2.23606798, 2.23606798, 2.23606798]])

In [128]:
np.log10(arr7) ## in case of log we can only perform log with base 10

array([[0.47712125, 0.47712125, 0.47712125, 0.47712125],
       [0.60205999, 0.60205999, 0.60205999, 0.60205999],
       [0.69897   , 0.69897   , 0.69897   , 0.69897   ]])

In [129]:
np.exp(arr7)

array([[ 20.08553692,  20.08553692,  20.08553692,  20.08553692],
       [ 54.59815003,  54.59815003,  54.59815003,  54.59815003],
       [148.4131591 , 148.4131591 , 148.4131591 , 148.4131591 ]])

In [130]:
np.min(arr7)

3.0

In [131]:
np.max(arr7)

5.0

# Numpy - part 3

In [1]:
import numpy as np

## Numpy array Manipulation

In [4]:
arr=np.random.randint(1,10,(4,4))

In [5]:
arr.reshape(8,2)

array([[2, 1],
       [5, 9],
       [7, 2],
       [4, 2],
       [6, 1],
       [1, 4],
       [6, 2],
       [1, 1]])

In [7]:
arr

array([[2, 1, 5, 9],
       [7, 2, 4, 2],
       [6, 1, 1, 4],
       [6, 2, 1, 1]])

In [8]:
arr.T

array([[2, 7, 6, 6],
       [1, 2, 1, 2],
       [5, 4, 1, 1],
       [9, 2, 4, 1]])

In [27]:
arr.flatten() ## it create flat array all the elements in a one row i.e. one dimensional array

array([2, 1, 5, 9, 7, 2, 4, 2, 6, 1, 1, 4, 6, 2, 1, 1])

In [12]:
arr

array([[2, 1, 5, 9],
       [7, 2, 4, 2],
       [6, 1, 1, 4],
       [6, 2, 1, 1]])

In [29]:
## in this fun dimension of the array is increased by 1 i.e. 2 dimension covverted into 3 dimesion 
## the maximum it can convert into 3 dimension array 
np.expand_dims(arr,axis=1)  ### axis= 1 it means that it will perform column wise operation

array([[[2, 1, 5, 9]],

       [[7, 2, 4, 2]],

       [[6, 1, 1, 4]],

       [[6, 2, 1, 1]]])

In [30]:
np.expand_dims(arr,axis=0)  ### axis= 0 it means that it will perform row wise operation

array([[[2, 1, 5, 9],
        [7, 2, 4, 2],
        [6, 1, 1, 4],
        [6, 2, 1, 1]]])

In [31]:
data  = np.array(list([[1],[2],[3]]))

In [33]:
np.squeeze(data)  ## it will convert 2 dimensional array to 1 dimensional array

array([1, 2, 3])

In [39]:
np.repeat(data,10) # This fun repeats the all elemets as we assign th no of repetation

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 3, 3,
       3, 3, 3, 3, 3, 3, 3, 3])

In [43]:
#This fun rotates the given data after the number we assign i.e it roll a elements in a circular way i.e. 0 to n and n to 0
# for zero index it will be 0+2 i.e. for index one it is 1+2 but here 3rd position is not avaliable so it will be again zero
np.roll(data,2)

array([[2],
       [3],
       [1]])

In [49]:
np.diag(np.array([1,2,3,4])) ### it will create an diagonal array with all element in passing array as a diagonal element

array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 4]])

## Numpy - Binary Operations

In [53]:
arr1 =np.random.randint(1,10,(3,4))
arr2 =np.random.randint(1,10,(3,4))

In [54]:
arr1

array([[9, 1, 3, 6],
       [4, 6, 3, 4],
       [6, 2, 2, 3]])

In [55]:
arr2

array([[6, 3, 1, 7],
       [7, 4, 1, 7],
       [5, 9, 5, 2]])

In [56]:
arr1+arr2 ## it will give addition by index wise

array([[15,  4,  4, 13],
       [11, 10,  4, 11],
       [11, 11,  7,  5]])

In [57]:
arr1*arr2 ## it will give multiplition by index wise

array([[54,  3,  3, 42],
       [28, 24,  3, 28],
       [30, 18, 10,  6]])

In [58]:
arr1/arr2 ## it will give divition by index wise

array([[1.5       , 0.33333333, 3.        , 0.85714286],
       [0.57142857, 1.5       , 3.        , 0.57142857],
       [1.2       , 0.22222222, 0.4       , 1.5       ]])

In [59]:
arr1-arr2 ## it will give subtraction by index wise

array([[ 3, -2,  2, -1],
       [-3,  2,  2, -3],
       [ 1, -7, -3,  1]])

In [62]:
arr1**arr2 ## it will perform power opration  by index wise

array([[531441,      1,      3, 279936],
       [ 16384,   1296,      3,  16384],
       [  7776,    512,     32,      9]])

In [60]:
~arr1 ## it will convert all positive value into negative vlaues

array([[-10,  -2,  -4,  -7],
       [ -5,  -7,  -4,  -5],
       [ -7,  -3,  -3,  -4]])

In [61]:
arr1

array([[9, 1, 3, 6],
       [4, 6, 3, 4],
       [6, 2, 2, 3]])

In [63]:
arr1>arr2 ##comparision opration

array([[ True, False,  True, False],
       [False,  True,  True, False],
       [ True, False, False,  True]])

## Numpy - String Operation

In [64]:
arr3 = np.asarray(["namit","chaudhari"])

In [66]:
arr3 ## data type <U9 it means its a string array

array(['namit', 'chaudhari'], dtype='<U9')

In [72]:
np.char.upper(arr3) ## char fun gives excess to all string funtions inside a numpy

array(['NAMIT', 'CHAUDHARI'], dtype='<U9')

In [73]:
np.char.capitalize(arr3)

array(['Namit', 'Chaudhari'], dtype='<U9')

In [74]:
np.char.title(arr3)

array(['Namit', 'Chaudhari'], dtype='<U9')

## Numpy - Mathmatical Function

In [76]:
arr1

array([[9, 1, 3, 6],
       [4, 6, 3, 4],
       [6, 2, 2, 3]])

In [ ]:
np.sin(arr1) ## This fun gives  sin values for all elemnts #trigomentry sin cos 

In [78]:
np.cos(arr1)  ## This fun gives cos values for all elemnts

array([[-0.91113026,  0.54030231, -0.9899925 ,  0.96017029],
       [-0.65364362,  0.96017029, -0.9899925 , -0.65364362],
       [ 0.96017029, -0.41614684, -0.41614684, -0.9899925 ]])

In [79]:
np.tan(arr)

array([[-2.18503986,  1.55740772, -3.38051501, -0.45231566],
       [ 0.87144798, -2.18503986,  1.15782128, -2.18503986],
       [-0.29100619,  1.55740772,  1.55740772,  1.15782128],
       [-0.29100619, -2.18503986,  1.55740772,  1.55740772]])

In [80]:
np.log10(arr)

array([[0.30103   , 0.        , 0.69897   , 0.95424251],
       [0.84509804, 0.30103   , 0.60205999, 0.30103   ],
       [0.77815125, 0.        , 0.        , 0.60205999],
       [0.77815125, 0.30103   , 0.        , 0.        ]])

In [82]:
np.exp(arr) ## it will give exponent of data

array([[7.38905610e+00, 2.71828183e+00, 1.48413159e+02, 8.10308393e+03],
       [1.09663316e+03, 7.38905610e+00, 5.45981500e+01, 7.38905610e+00],
       [4.03428793e+02, 2.71828183e+00, 2.71828183e+00, 5.45981500e+01],
       [4.03428793e+02, 7.38905610e+00, 2.71828183e+00, 2.71828183e+00]])

In [83]:
np.power(arr , 3) ## it will give power to every elemnt

array([[  8,   1, 125, 729],
       [343,   8,  64,   8],
       [216,   1,   1,  64],
       [216,   8,   1,   1]])

In [86]:
np.mean(arr) ## mean of whole data set

3.375

In [89]:
np.median(arr) ## middel value of array

2.0

In [91]:
np.std(arr) # standerd devisation 

2.4717149916606487

In [93]:
np.var(arr)

6.109375

In [94]:
np.min(arr)

1

In [95]:
np.max(arr)

9

 ## Numpy - Arthmatic Opretion

In [97]:
arr1


array([[9, 1, 3, 6],
       [4, 6, 3, 4],
       [6, 2, 2, 3]])

In [98]:
arr2 

array([[6, 3, 1, 7],
       [7, 4, 1, 7],
       [5, 9, 5, 2]])

In [99]:
arr1-arr2

array([[ 3, -2,  2, -1],
       [-3,  2,  2, -3],
       [ 1, -7, -3,  1]])

In [101]:
np.subtract(arr1,arr2) ## similar to arr1-arr2

array([[ 3, -2,  2, -1],
       [-3,  2,  2, -3],
       [ 1, -7, -3,  1]])

In [102]:
np.add(arr1,arr2)

array([[15,  4,  4, 13],
       [11, 10,  4, 11],
       [11, 11,  7,  5]])

In [103]:
np.multiply(arr1,arr2)

array([[54,  3,  3, 42],
       [28, 24,  3, 28],
       [30, 18, 10,  6]])

In [106]:
np.mod(arr1,arr2)  ## it will give reminder 

array([[3, 1, 0, 6],
       [4, 2, 0, 4],
       [1, 2, 2, 1]])

In [107]:
np.power(arr1,arr2)

array([[531441,      1,      3, 279936],
       [ 16384,   1296,      3,  16384],
       [  7776,    512,     32,      9]])

In [113]:
np.sqrt(arr1)

array([[3.        , 1.        , 1.73205081, 2.44948974],
       [2.        , 2.44948974, 1.73205081, 2.        ],
       [2.44948974, 1.41421356, 1.41421356, 1.73205081]])

## Numpy - Statical Funtion

In [114]:
np.mean(arr1)

4.083333333333333

In [115]:
np.median(arr1)

3.5

In [116]:
np.std(arr1)

2.1778557242286634

# Numpy part 4 

In [2]:
import numpy as np

## Sort ,Search & Continuous Functions

In [3]:
arr = np.array([6,8,5,3,7,4,9,5,6,9])

In [4]:
arr

array([6, 8, 5, 3, 7, 4, 9, 5, 6, 9])

In [5]:
np.sort(arr)

array([3, 4, 5, 5, 6, 6, 7, 8, 9, 9])

In [6]:
np.searchsorted(arr,2) ## this function tells us where we can put our data in which index we can placeit 

0

In [8]:
arr1=np.array([0,3,4,5,6,0,0,256,365])

In [9]:
arr1

array([  0,   3,   4,   5,   6,   0,   0, 256, 365])

In [11]:
np.count_nonzero(arr1) ## it tell the count of non zero element

6

In [13]:
np.where(arr1>0) ## it tell the indexes at what indexes the given condition is true

(array([1, 2, 3, 4, 7, 8]),)

In [15]:
np.extract(arr1>2,arr1) #it will excrat all the data at which the condition is true

array([  3,   4,   5,   6, 256, 365])

## Numpy - Byte Swapping

In [16]:
arr1

array([  0,   3,   4,   5,   6,   0,   0, 256, 365])

In [19]:
arr1.byteswap() ### it gives the byte information if we pass inplace = True then it will be perment

array([                  0,  216172782113783808,  288230376151711744,
        360287970189639680,  432345564227567616,                   0,
                         0,     281474976710656, 7854559225110855680])

## Numpy - Copies & Views

In [20]:
arr1

array([  0,   3,   4,   5,   6,   0,   0, 256, 365])

In [32]:
a=np.copy(arr1) ## It is a deep copy

In [22]:
a

array([  0,   3,   4,   5,   6,   0,   0, 256, 365])

In [23]:
a[0]=100

In [24]:
a

array([100,   3,   4,   5,   6,   0,   0, 256, 365])

In [26]:
arr1

array([  0,   3,   4,   5,   6,   0,   0, 256, 365])

In [33]:
b = arr1.view() ## it is a solo copy

In [34]:
b

array([234,   3,   4,   5,   6,   0,   0, 256, 365])

In [35]:
b[0]=234

In [36]:
b

array([234,   3,   4,   5,   6,   0,   0, 256, 365])

In [37]:
arr1

array([234,   3,   4,   5,   6,   0,   0, 256, 365])

## Numpy - Matrix Libary

In [38]:
import numpy.matlib as nm

In [39]:
nm.zeros(5)

matrix([[0., 0., 0., 0., 0.]])

In [42]:
nm.ones((3,4))

matrix([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [43]:
nm.eye(4)

matrix([[1., 0., 0., 0.],
        [0., 1., 0., 0.],
        [0., 0., 1., 0.],
        [0., 0., 0., 1.]])

In [44]:
## Numpy - Linear Algeebra

In [51]:
arr2 = np.random.randint([[2,3],[4,5]])

In [52]:
arr3 = np.random.randint([[5,3],[2,5]])

In [55]:
arr3

array([[2, 0],
       [0, 3]])

In [54]:
arr2

array([[0, 0],
       [3, 3]])

In [59]:
np.dot(arr2,arr3) ## it is a simple matrix multiplication

array([[0, 0],
       [6, 9]])

In [58]:
arr2@arr3

array([[0, 0],
       [6, 9]])