## information notebook is present in data science/pwnotes/5-6


# TensorFlow

In [1]:
pip install tensorflow

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 489.8/489.8 MB 3.2 MB/s eta 0:00:0000:0100:01
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 77.9/77.9 kB 13.4 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 57.5/57.5 kB 11.9 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 5.5/5.5 MB 71.8 MB/s eta 0:00:00:00:0100:01
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 130.2/130.2 kB 19.7 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 65.5/65.5 kB 11.0 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.0/1.0 MB 62.1 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 5.3/5.3 MB 72.5 MB/s eta 0:00:00:00:0100:01
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.7/1.7 MB 71.2 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 22.9/22.9 MB 52.7 MB/s eta 0:00:0000:0100:01
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 440.7/440.7 kB 46.0 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.4/2.4 MB 75.7 MB/s eta 0:00

In [2]:
pip install keras

Note: you may need to restart the kernel to use updated packages.


In [6]:
## Version Check
import tensorflow as tf
import keras
print('tensorflow version {}'.format(tf.__version__))
print('Eager Execution is : {}'.format(tf.executing_eagerly()))
print('keras version : {}'.format(keras.__version__))

tensorflow version 2.14.0
Eager Execution is : True
keras version : 2.14.0


In [5]:
ineuron=tf.constant(42)
ineuron

<tf.Tensor: shape=(), dtype=int32, numpy=42>

In [6]:
ineuron.numpy()

42

In [7]:
ineuron1=tf.constant(1,dtype=tf.int64)
ineuron1.numpy()

1

In [19]:
ineuron_X=tf.constant([(2,2),(5,5)])

In [20]:
print(ineuron_X)

tf.Tensor(
[[2 2]
 [5 5]], shape=(2, 2), dtype=int32)


In [10]:
print(ineuron_X.numpy(),'\n')
print(ineuron_X.shape,'\n')
print(ineuron_X.dtype)

[[2 2]
 [5 5]] 

(2, 2) 

<dtype: 'int32'>


In [11]:
## genrrating Constants 
print(tf.ones(shape=(2,3)))

tf.Tensor(
[[1. 1. 1.]
 [1. 1. 1.]], shape=(2, 3), dtype=float32)


In [12]:
print(tf.zeros(shape=(2,3)))

tf.Tensor(
[[0. 0. 0.]
 [0. 0. 0.]], shape=(2, 3), dtype=float32)


In [13]:
## Adding two Constansts 
con1=tf.constant([[4,5,6],[4,5,6]])
con2=tf.constant([[1,2,3],[1,2,3]])
result=tf.add(con1,con2)
print(result)

tf.Tensor(
[[5 7 9]
 [5 7 9]], shape=(2, 3), dtype=int32)


In [14]:
### Declearring Constants Randomly 
## using Normal Distributtion
tf.random.normal(shape=(2,2),mean=5,stddev=10)

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[ 8.338776 , 11.090475 ],
       [ 6.5484014,  6.731309 ]], dtype=float32)>

In [15]:
## using uniform Distribusion
tf.random.uniform(shape=(3,3),minval=0,maxval=10,dtype=tf.int64)

<tf.Tensor: shape=(3, 3), dtype=int64, numpy=
array([[4, 0, 4],
       [2, 8, 9],
       [9, 3, 2]])>

In [16]:
## variables in tensor
var0 = 24 # python Variable
var1 = tf.Variable(42) ## rank 0 tensor
var2 = tf.Variable([[[1.,2.,3.],[4.,5.,6.]],[[7.,8.,9.],[2.,5.,6]]]) ## rank 3 tensor

### Rank is basically no of indices or the no of dimensions

In [17]:
var0,var1,var2

(24,
 <tf.Variable 'Variable:0' shape=() dtype=int32, numpy=42>,
 <tf.Variable 'Variable:0' shape=(2, 2, 3) dtype=float32, numpy=
 array([[[1., 2., 3.],
         [4., 5., 6.]],
 
        [[7., 8., 9.],
         [2., 5., 6.]]], dtype=float32)>)

In [18]:
### Reassigning the values
variable1=tf.Variable(52)
variable1

<tf.Variable 'Variable:0' shape=() dtype=int32, numpy=52>

In [19]:
variable1.assign(34)
variable1

<tf.Variable 'Variable:0' shape=() dtype=int32, numpy=34>

In [20]:
tensor=tf.Variable([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])

In [21]:
tensor1=tf.reshape(tensor,(2,6))

In [22]:
tensor1

<tf.Tensor: shape=(2, 6), dtype=int32, numpy=
array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12]], dtype=int32)>

In [23]:
tensor2=tf.reshape(tensor,(1,12))

In [24]:
tensor2

<tf.Tensor: shape=(1, 12), dtype=int32, numpy=array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12]], dtype=int32)>

In [25]:
## How to Know the ranking of the Tensor
print(tf.rank(tensor))
print('\n')
print(tf.rank(tensor1))
print('\n')
print(tf.rank(tensor2))
print('\n')
## to get the direct value of rank use numpy
print(tf.rank(tensor).numpy())

tf.Tensor(3, shape=(), dtype=int32)


tf.Tensor(2, shape=(), dtype=int32)


tf.Tensor(2, shape=(), dtype=int32)


3


In [26]:
tensor3 = tensor[1,0,2]
tensor3

<tf.Tensor: shape=(), dtype=int32, numpy=9>

In [27]:
print(tensor.numpy())

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


In [28]:
## finding size of an array is bascially a no of elements in the array

In [29]:
tensor_size=tf.size(tensor).numpy()

In [30]:
tensor_size

12

In [31]:
## some Mathametical operations
a=tf.random.normal(shape=(2,2),mean=20,stddev=5)
b=tf.random.normal(shape=(2,2),mean=20,stddev=5)
c=a+b
d=tf.square(c)
e=tf.exp(c)
print(a)
print(b)
print(c)
print(d)
print(e)

tf.Tensor(
[[16.841389 12.927839]
 [20.863482 19.250078]], shape=(2, 2), dtype=float32)
tf.Tensor(
[[27.939213 20.781715]
 [19.003704 25.014366]], shape=(2, 2), dtype=float32)
tf.Tensor(
[[44.7806   33.709557]
 [39.867188 44.264442]], shape=(2, 2), dtype=float32)
tf.Tensor(
[[2005.3022 1136.3342]
 [1589.3926 1959.3408]], shape=(2, 2), dtype=float32)
tf.Tensor(
[[2.8052278e+19 4.3638962e+14]
 [2.0611022e+17 1.6741837e+19]], shape=(2, 2), dtype=float32)


In [32]:
tensor*tensor

<tf.Tensor: shape=(2, 2, 3), dtype=int32, numpy=
array([[[  1,   4,   9],
        [ 16,  25,  36]],

       [[ 49,  64,  81],
        [100, 121, 144]]], dtype=int32)>

In [33]:
tensor

<tf.Variable 'Variable:0' shape=(2, 2, 3) dtype=int32, numpy=
array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]], dtype=int32)>

In [34]:
tensor4=tensor*5

In [35]:
tensor4

<tf.Tensor: shape=(2, 2, 3), dtype=int32, numpy=
array([[[ 5, 10, 15],
        [20, 25, 30]],

       [[35, 40, 45],
        [50, 55, 60]]], dtype=int32)>

In [36]:
## Tensor casting
print(tensor1)
i=tf.cast(tensor1,dtype=tf.float32)
print(i)

tf.Tensor(
[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]], shape=(2, 6), dtype=int32)
tf.Tensor(
[[ 1.  2.  3.  4.  5.  6.]
 [ 7.  8.  9. 10. 11. 12.]], shape=(2, 6), dtype=float32)


In [37]:
j=tf.cast(tf.constant(4.9),dtype=tf.int32).numpy()
print(j)

4


In [38]:
## Ragged Tensor it inclues any shapes of row in tensor
ragged=tf.ragged.constant([[1,2,3,6,5],[],[23,26,52],[1],[0,223,22,2222,22]])
print(ragged)
print(ragged[0,:])
print(ragged[1,:])
print(ragged[2,:])
print(ragged[3,:])
print(ragged[4,:])

<tf.RaggedTensor [[1, 2, 3, 6, 5], [], [23, 26, 52], [1], [0, 223, 22, 2222, 22]]>
tf.Tensor([1 2 3 6 5], shape=(5,), dtype=int32)
tf.Tensor([], shape=(0,), dtype=int32)
tf.Tensor([23 26 52], shape=(3,), dtype=int32)
tf.Tensor([1], shape=(1,), dtype=int32)
tf.Tensor([   0  223   22 2222   22], shape=(5,), dtype=int32)


In [39]:
## finding squared difference between tensor
varX=[1,2,3,6,5,4,6]
varY=5
varz=tf.math.squared_difference(varX,varY)

In [40]:
varz

<tf.Tensor: shape=(7,), dtype=int32, numpy=array([16,  9,  4,  1,  0,  1,  1], dtype=int32)>

In [41]:
#### finding Mean of tensor
numbers=tf.constant([[1.,2.],[3.,4.],[5.,6.]])
tf.reduce_mean(numbers)

<tf.Tensor: shape=(), dtype=float32, numpy=3.5>

In [42]:
## finding mean alongs the columns 
tf.reduce_mean(numbers,axis=0)

<tf.Tensor: shape=(2,), dtype=float32, numpy=array([3., 4.], dtype=float32)>

In [43]:
### while columns mean we loseing some dimensions to overcome these we use keepdim=True
tf.reduce_mean(numbers,axis=0,keepdims=True)

<tf.Tensor: shape=(1, 2), dtype=float32, numpy=array([[3., 4.]], dtype=float32)>

In [44]:
## finding mean alongs the rows
tf.reduce_mean(numbers,axis=1)

<tf.Tensor: shape=(3,), dtype=float32, numpy=array([1.5, 3.5, 5.5], dtype=float32)>

In [45]:
### Setting seed it is like a random state by setting a seed we can regenrate the same set of data again and again

In [46]:
tf.random.normal(shape=(3,2),mean=10,stddev=2,dtype=tf.float32,seed=None ,name=None)

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[13.471383,  9.830491],
       [ 9.815726, 10.357299],
       [ 6.684596, 10.861412]], dtype=float32)>

In [47]:
## Seed helps us to regenrate the random value which we are genrating previous one

In [48]:
## Setting the seed 

In [49]:
tf.random.set_seed(11)
ran1=tf.random.normal(shape=(3,5))
ran2=tf.random.normal(shape=(4,3))
print(ran1)
print(ran2)

tf.Tensor(
[[-1.5229472   0.66954476 -0.6424697   1.4300429   0.5867822 ]
 [ 0.4392982   0.06769665  1.4841088  -0.10583612  1.7886113 ]
 [-1.3436369   0.1916718   0.1465998  -1.2674419  -1.0966402 ]], shape=(3, 5), dtype=float32)
tf.Tensor(
[[ 0.35981855  1.0180439  -2.0297976 ]
 [-0.7807032   2.6000936   0.6251627 ]
 [ 1.5736731  -1.5090868  -0.08556824]
 [-0.27837607 -0.00504523  1.2153692 ]], shape=(4, 3), dtype=float32)


In [66]:
t5 = tf.constant([2,11,5,42,7,19,-6,-11,29])
print(t5)

i = tf.argmax(input=t5)
print(f"index of max :{i}")
print("maximum number is :",t5[i].numpy())

j = tf.argmin(input=t5)
print(f"index of max :{j}")
print("maximum number is :",t5[j].numpy())

t6=tf.reshape(t5,[3,3])
print(t6)

i = tf.argmax(input=t6,axis=1).numpy()
print(f"In t6 columnwise Index of maximum number is {i} ")

i = tf.argmin(input=t6,axis=1).numpy()
print(f"In t6 columnwise Index of minimum number is {i} ")

i = tf.argmin(input=t6,axis=0).numpy()
print(f"In t6 rowwise Index of maximum number is {i} ")

i = tf.argmax(input=t6,axis=0).numpy()
print(f"In t6 rowwise Index of minimum number is {i} ")

tf.Tensor([  2  11   5  42   7  19  -6 -11  29], shape=(9,), dtype=int32)
index of max :3
maximum number is : 42
index of max :7
maximum number is : -11
tf.Tensor(
[[  2  11   5]
 [ 42   7  19]
 [ -6 -11  29]], shape=(3, 3), dtype=int32)
In t6 columnwise Index of maximum number is [1 0 2] 
In t6 columnwise Index of minimum number is [0 1 1] 
In t6 rowwise Index of maximum number is [2 2 0] 
In t6 rowwise Index of minimum number is [1 0 2] 


In [67]:
### Saving and restoring tensor values using a checkpoint 

In [5]:
variable = tf.Variable([[1,2,3,4,5],[7,8,9,10,11]])
checkpoint=tf.train.Checkpoint(var=variable)
save_path=checkpoint.save('./vars')
variable.assign([[0,0,0,0,0],[0,0,0,0,0]])
print(variable)
checkpoint.restore(save_path)
print(variable)

<tf.Variable 'Variable:0' shape=(2, 5) dtype=int32, numpy=
array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]], dtype=int32)>
<tf.Variable 'Variable:0' shape=(2, 5) dtype=int32, numpy=
array([[ 1,  2,  3,  4,  5],
       [ 7,  8,  9, 10, 11]], dtype=int32)>


In [10]:
## use of tf.function

In [11]:
def f1(x,y):
    return(tf.reduce_mean(input_tensor=tf.multiply(x**2 ,5 )+y**2))

x=tf.constant([4.,-5.])
y=tf.constant([2.,3.])

f1(x,y)

<tf.Tensor: shape=(), dtype=float32, numpy=109.0>

In [12]:
## Calculate the Gradent 

In [17]:
a=tf.random.normal(shape=(2,2))
b=tf.random.normal(shape=(2,2))

with tf.GradientTape() as tape:
    tape.watch(a)
    c=tf.sqrt(tf.square(a),tf.square(b))
    dc_da= tape.gradient(c,a) ## Calculating Gradient 
    print(dc_da)


tf.Tensor(
[[-1.  1.]
 [ 1. -1.]], shape=(2, 2), dtype=float32)


In [18]:
with tf.GradientTape() as Outer_tape:
    with tf.GradientTape() as tape:
        tape.watch(a)
        c=tf.sqrt(tf.square(a),tf.square(b))
        dc_da= tape.gradient(c,a) ## Calculating Gradient 
        print(dc_da)
        d2c_da2 = Outer_tape.gradient(dc_da,a)  ## calculating second Derivative
        print(d2c_da2)

tf.Tensor(
[[-1.  1.]
 [ 1. -1.]], shape=(2, 2), dtype=float32)
None


# Pytorch

In [4]:
pip install torch

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 619.9/619.9 MB 2.2 MB/s eta 0:00:0000:0100:01
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 98.6/98.6 kB 16.0 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 21.0/21.0 MB 54.6 MB/s eta 0:00:0000:0100:01
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 168.4/168.4 MB 12.9 MB/s eta 0:00:0000:0100:01
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 54.6/54.6 MB 33.7 MB/s eta 0:00:0000:0100:01
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 63.3/63.3 MB 30.2 MB/s eta 0:00:0000:0100:01
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 11.8/11.8 MB 62.4 MB/s eta 0:00:0000:010:01
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 849.3/849.3 kB 56.5 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 102.6/102.6 MB 14.1 MB/s eta 0:00:0000:0100:01
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 177.1/177.1 MB 5.5 MB/s eta 0:00:0000:0100:02
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 173.2/173.2 MB 8.3 MB/s eta 0:00:0000:0100:01
     ━━━━━━━━━━━━━━━

In [1]:
import torch

In [2]:
t1=torch.tensor(4.)
t1

tensor(4.)

In [3]:
t1.dtype

torch.float32

In [4]:
# vector or 1d array
t2 = torch.tensor([1,2,3,4,5,6])
t2

tensor([1, 2, 3, 4, 5, 6])

In [5]:
# 2 dimensional array or matrix
t3 = torch.tensor([[5.,6.],[7.,8.],[9.,10.]])
t3

tensor([[ 5.,  6.],
        [ 7.,  8.],
        [ 9., 10.]])

In [6]:
# Multidimensional array
t4 = torch.tensor([[[11,12,13],[14,15,16]],[[17,18,19],[20,21,22]]])
t4

tensor([[[11, 12, 13],
         [14, 15, 16]],

        [[17, 18, 19],
         [20, 21, 22]]])

In [7]:
print(t1)
t1.shape

tensor(4.)


torch.Size([])

In [8]:
print(t2)
t2.shape

tensor([1, 2, 3, 4, 5, 6])


torch.Size([6])

In [9]:
print(t3)
t3.shape

tensor([[ 5.,  6.],
        [ 7.,  8.],
        [ 9., 10.]])


torch.Size([3, 2])

In [10]:
print(t4)
t4.shape

tensor([[[11, 12, 13],
         [14, 15, 16]],

        [[17, 18, 19],
         [20, 21, 22]]])


torch.Size([2, 2, 3])

In [11]:
x = torch.tensor(4.)
#"requires_grad" if this parameter we set it as a true then we can differeciate any expression with repect to that variable
w = torch.tensor(5.,requires_grad=True)
b = torch.tensor(6.,requires_grad=True)
x,w,b

(tensor(4.), tensor(5., requires_grad=True), tensor(6., requires_grad=True))

In [12]:
## Consider we have an expression or an Arithmetic operation
y = w * x + b
y

tensor(26., grad_fn=<AddBackward0>)

In [13]:
y.backward() ### it finds all the possible derivatives

In [14]:
print(x.grad)

None


In [15]:
print(w.grad)

tensor(4.)


In [16]:
print(b.grad)

tensor(1.)


In [17]:
## Functions in Tensor

In [18]:
## Creating a tensor which is full with one same element
t6 = torch.full((3,2),42)
print(t6)

tensor([[42, 42],
        [42, 42],
        [42, 42]])


In [21]:
## Concatinate 
t7 = torch.concat([t6,t3])
print(t7)

tensor([[42., 42.],
        [42., 42.],
        [42., 42.],
        [ 5.,  6.],
        [ 7.,  8.],
        [ 9., 10.]])


In [22]:
## Compute the sin of each element of a tensor
t8 = torch.sin(t7)
print(t8)

tensor([[-0.9165, -0.9165],
        [-0.9165, -0.9165],
        [-0.9165, -0.9165],
        [-0.9589, -0.2794],
        [ 0.6570,  0.9894],
        [ 0.4121, -0.5440]])


In [23]:
### changing the shape of tensor 
t9 = t8.reshape(3,2,2)
print(t9)

tensor([[[-0.9165, -0.9165],
         [-0.9165, -0.9165]],

        [[-0.9165, -0.9165],
         [-0.9589, -0.2794]],

        [[ 0.6570,  0.9894],
         [ 0.4121, -0.5440]]])


In [24]:
## Connection with numpy

In [25]:
import numpy as np

In [30]:
x = np.array([[3.,6.,9.],[2.,4.,5.]])
print(x)

[[3. 6. 9.]
 [2. 4. 5.]]


In [34]:
# from numpy to torch
y = torch.from_numpy(x)
print(y)

tensor([[3., 6., 9.],
        [2., 4., 5.]], dtype=torch.float64)


In [35]:
x.dtype , y.dtype

(dtype('float64'), torch.float64)

In [36]:
# from torch to numpy
z = y.numpy()
print(z)

[[3. 6. 9.]
 [2. 4. 5.]]


In [37]:
## Linear regression 

In [39]:
import numpy as np 
import torch

In [40]:
# making training data 
# input (temp , rainfall  , humidity)
inputs = np.array([[73,67,43],
                  [91,88,64],
                  [87,134,58],
                  [102,43,37],
                  [69,96,70]],dtype='float32')

In [41]:
# targets (apples and oranges)
target = np.array([[56,70],
                  [81,101],
                  [119,133],
                  [22,37],
                  [103,119]],dtype='float32')

In [42]:
## convert it into a torch array
inputs = torch.from_numpy(inputs)
target = torch.from_numpy(target)

print(inputs,'\n')
print(target)

tensor([[ 73.,  67.,  43.],
        [ 91.,  88.,  64.],
        [ 87., 134.,  58.],
        [102.,  43.,  37.],
        [ 69.,  96.,  70.]]) 

tensor([[ 56.,  70.],
        [ 81., 101.],
        [119., 133.],
        [ 22.,  37.],
        [103., 119.]])


In [43]:
## Weights and biaes 
w = torch.randn(2,3,requires_grad=True)
b = torch.randn(2,requires_grad=True)

print(w)
print(b)

tensor([[-0.0761,  0.3807, -1.3061],
        [-1.6619,  0.7192,  0.2594]], requires_grad=True)
tensor([0.6157, 0.0969], requires_grad=True)


In [44]:
## define model 
def model(x):
    return x @ w.t() + b

In [45]:
## preiction 
preds = model(inputs)
print(preds)

tensor([[ -35.5964,  -61.8761],
        [ -56.3999,  -71.2380],
        [ -30.7460,  -33.0633],
        [ -39.1048, -128.8881],
        [ -59.5159,  -27.3666]], grad_fn=<AddBackward0>)


In [46]:
# actual 
print(target)

tensor([[ 56.,  70.],
        [ 81., 101.],
        [119., 133.],
        [ 22.,  37.],
        [103., 119.]])


In [47]:
## loss function MSE 
def MSE(actual , target):
    diff = actual - target
    return torch.sum(diff**2)/diff.numel()

In [48]:
## Error 
loss = MSE(target,preds)
print(loss)

tensor(20341.4082, grad_fn=<DivBackward0>)


In [49]:
## Compute gradient
loss.backward()

In [50]:
print(w,'\n')
print(w.grad)

tensor([[-0.0761,  0.3807, -1.3061],
        [-1.6619,  0.7192,  0.2594]], requires_grad=True) 

tensor([[ -9932.8252, -11304.6318,  -7010.9004],
        [-13353.6016, -13485.9014,  -8541.8203]])


In [51]:
print(b,'\n')
print(b.grad)

tensor([0.6157, 0.0969], requires_grad=True) 

tensor([-120.4726, -156.4864])


In [52]:
## Netural Network Using Pytorch

In [72]:
import torch
from torch import nn
from torch.utils.data import DataLoader
import torchvision
from torchvision import datasets
from torchvision.transforms import ToTensor , Lambda , Compose
import matplotlib.pyplot as plt

In [73]:
## downloading data from datasets
training_data = datasets.FashionMNIST(
    root="data",
    download=True,
    train=True,
    transform=ToTensor(),
)

test_data = datasets.FashionMNIST(
    root='data',
    download=True,
    train=False,
    transform=ToTensor(),
)

100%|██████████| 26421880/26421880 [00:02<00:00, 9378389.29it/s] 


Extracting data/FashionMNIST/raw/train-images-idx3-ubyte.gz to data/FashionMNIST/raw



100%|██████████| 29515/29515 [00:00<00:00, 231479.27it/s]


Extracting data/FashionMNIST/raw/train-labels-idx1-ubyte.gz to data/FashionMNIST/raw



100%|██████████| 4422102/4422102 [00:01<00:00, 4272263.77it/s]


Extracting data/FashionMNIST/raw/t10k-images-idx3-ubyte.gz to data/FashionMNIST/raw



100%|██████████| 5148/5148 [00:00<00:00, 8647287.54it/s]

Extracting data/FashionMNIST/raw/t10k-labels-idx1-ubyte.gz to data/FashionMNIST/raw



In [76]:
batch_size = 64 
## Create data loaders
train_dataloader = DataLoader(training_data,batch_size=batch_size)
test_dataloader = DataLoader(test_data,batch_size=batch_size)

for X, y in test_dataloader:
    print("Shape of X [N ,C , H , W]:",X.shape)
    print("Shape of y :",y.shape , y.dtype)
    break

Shape of X [N ,C , H , W]: torch.Size([64, 1, 28, 28])
Shape of y : torch.Size([64]) torch.int64


In [78]:
# Get cpu or gpu device for training.
device = "cuda" if torch.cuda.is_available() else "cpu"
print(f"Using {device} device")

Using cpu device


In [79]:
# Define model
class NeuralNetwork(nn.Module):
    def __init__(self):
        super(NeuralNetwork, self).__init__()
        self.flatten = nn.Flatten()
        self.linear_relu_stack = nn.Sequential(
            nn.Linear(28*28, 512),
            nn.ReLU(),
            nn.Linear(512, 512),
            nn.ReLU(),
            nn.Linear(512, 10)
        )

    def forward(self, x):
        x = self.flatten(x)
        logits = self.linear_relu_stack(x)
        return logits

model = NeuralNetwork().to(device)
print(model)

NeuralNetwork(
  (flatten): Flatten(start_dim=1, end_dim=-1)
  (linear_relu_stack): Sequential(
    (0): Linear(in_features=784, out_features=512, bias=True)
    (1): ReLU()
    (2): Linear(in_features=512, out_features=512, bias=True)
    (3): ReLU()
    (4): Linear(in_features=512, out_features=10, bias=True)
  )
)


In [80]:
loss_fn = nn.CrossEntropyLoss()
optimizer = torch.optim.SGD(model.parameters(), lr=1e-3)

In [81]:
def train(dataloader, model, loss_fn, optimizer):
    size = len(dataloader.dataset)
    model.train()
    for batch, (X, y) in enumerate(dataloader):
        X, y = X.to(device), y.to(device)

        # Compute prediction error
        pred = model(X)
        loss = loss_fn(pred, y)

        # Backpropagation
        optimizer.zero_grad()
        loss.backward()
        optimizer.step()

        if batch % 100 == 0:
            loss, current = loss.item(), batch * len(X)
            print(f"loss: {loss:>7f}  [{current:>5d}/{size:>5d}]")

In [82]:
def test(dataloader, model, loss_fn):
    size = len(dataloader.dataset)
    num_batches = len(dataloader)
    model.eval()
    test_loss, correct = 0, 0
    with torch.no_grad():
        for X, y in dataloader:
            X, y = X.to(device), y.to(device)
            pred = model(X)
            test_loss += loss_fn(pred, y).item()
            correct += (pred.argmax(1) == y).type(torch.float).sum().item()
    test_loss /= num_batches
    correct /= size
    print(f"Test Error: \n Accuracy: {(100*correct):>0.1f}%, Avg loss: {test_loss:>8f} \n")

In [83]:
epochs = 5
for t in range(epochs):
    print(f"Epoch {t+1}\n-------------------------------")
    train(train_dataloader, model, loss_fn, optimizer)
    test(test_dataloader, model, loss_fn)
print("Done!")

Epoch 1
-------------------------------
loss: 2.293810  [    0/60000]
loss: 2.278165  [ 6400/60000]
loss: 2.255163  [12800/60000]
loss: 2.250420  [19200/60000]
loss: 2.238439  [25600/60000]
loss: 2.194814  [32000/60000]
loss: 2.216641  [38400/60000]
loss: 2.169106  [44800/60000]
loss: 2.173702  [51200/60000]
loss: 2.137214  [57600/60000]
Test Error: 
 Accuracy: 43.3%, Avg loss: 2.123531 

Epoch 2
-------------------------------
loss: 2.138011  [    0/60000]
loss: 2.118599  [ 6400/60000]
loss: 2.055245  [12800/60000]
loss: 2.075497  [19200/60000]
loss: 2.021324  [25600/60000]
loss: 1.948467  [32000/60000]
loss: 1.983830  [38400/60000]
loss: 1.891984  [44800/60000]
loss: 1.906420  [51200/60000]
loss: 1.824737  [57600/60000]
Test Error: 
 Accuracy: 51.5%, Avg loss: 1.820021 

Epoch 3
-------------------------------
loss: 1.862230  [    0/60000]
loss: 1.819202  [ 6400/60000]
loss: 1.700981  [12800/60000]
loss: 1.747495  [19200/60000]
loss: 1.644891  [25600/60000]
loss: 1.592160  [32000/600

In [84]:
#save model
torch.save(model.state_dict(), "model.pth")
print("Saved PyTorch Model State to model.pth")

Saved PyTorch Model State to model.pth


In [85]:
#load model
model = NeuralNetwork()
model.load_state_dict(torch.load("model.pth"))

<All keys matched successfully>

In [86]:
## Prediction

classes = [
    "T-shirt/top",
    "Trouser",
    "Pullover",
    "Dress",
    "Coat",
    "Sandal",
    "Shirt",
    "Sneaker",
    "Bag",
    "Ankle boot",
]

model.eval()
x, y = test_data[0][0], test_data[0][1]
with torch.no_grad():
    pred = model(x)
    predicted, actual = classes[pred[0].argmax(0)], classes[y]
    print(f'Predicted: "{predicted}", Actual: "{actual}"')

Predicted: "Ankle boot", Actual: "Ankle boot"
