## Indrodution TO Deep Learing 

## Neural Network, Perceptron Mathematical Explanation

In [1]:
import numpy as np
import pandas as pd

In [4]:
class Perceptron:
    def __init__(self, eta, epochs):
        self.weights = np.random.randn(3) * 1e-4
        print(f"self.weights: {self.weights}")
        self.eta = eta
        self.epochs = epochs

    def activationFunction(self, inputs, weights):
        z = np.dot(inputs, weights)
        return np.where(z > 0 , 1, 0)

    def fit(self, X, y):
        self.X = X
        self.y = y

        X_with_bias = np.c_[self.X, -np.ones((len(self.X), 1))] # concactination
        print(f"X_with_bias: \n{X_with_bias}")

        for epoch in range(self.epochs):
            print(f"for epoch: {epoch}")
            y_hat = self.activationFunction(X_with_bias, self.weights)
            print(f"predicted value: \n{y_hat}")
            error = self.y - y_hat
            print(f"error: \n{error}")
            self.weights = self.weights + self.eta * np.dot(X_with_bias.T, error)
            print(f"updated weights: \n{self.weights}")
            print("#############\n")

    def predict(self, X):
        X_with_bias = np.c_[X, -np.ones((len(self.X), 1))]
        return self.activationFunction(X_with_bias, self.weights)

## AND OPERATION

In [5]:
data = {"x1": [0,0,1,1], "x2": [0,1,0,1], "y": [0,0,0,1]}

AND = pd.DataFrame(data)
AND

x1  x2  y
0   0   0  0
1   0   1  0
2   1   0  0
3   1   1  1

In [7]:
X = AND.drop("y", axis=1) 
X

x1  x2
0   0   0
1   0   1
2   1   0
3   1   1

In [8]:
y = AND['y']
y.to_frame()

y
0  0
1  0
2  0
3  1

In [26]:
model = Perceptron(eta = 0.5, epochs=10)
model.fit(X,y)

self.weights: [ 1.27202149e-04 -3.52712570e-05  2.44393925e-04]
X_with_bias: 
[[ 0.  0. -1.]
 [ 0.  1. -1.]
 [ 1.  0. -1.]
 [ 1.  1. -1.]]
for epoch: 0
predicted value: 
[0 0 0 0]
error: 
0    0
1    0
2    0
3    1
Name: y, dtype: int64
updated weights: 
[ 0.5001272   0.49996473 -0.49975561]
#############

for epoch: 1
predicted value: 
[1 1 1 1]
error: 
0   -1
1   -1
2   -1
3    0
Name: y, dtype: int64
updated weights: 
[ 1.27202149e-04 -3.52712570e-05  1.00024439e+00]
#############

for epoch: 2
predicted value: 
[0 0 0 0]
error: 
0    0
1    0
2    0
3    1
Name: y, dtype: int64
updated weights: 
[0.5001272  0.49996473 0.50024439]
#############

for epoch: 3
predicted value: 
[0 0 0 1]
error: 
0    0
1    0
2    0
3    0
Name: y, dtype: int64
updated weights: 
[0.5001272  0.49996473 0.50024439]
#############

for epoch: 4
predicted value: 
[0 0 0 1]
error: 
0    0
1    0
2    0
3    0
Name: y, dtype: int64
updated weights: 
[0.5001272  0.49996473 0.50024439]
#############

for epoc

In [30]:
model.predict(X)

array([0, 0, 0, 1])

In [29]:
model.weights

array([0.5001272 , 0.49996473, 0.50024439])

## XOR Operation:

In [31]:
data = {"x1": [0,0,1,1], "x2": [0,1,0,1], "y": [0,1,1,0]}

XOR = pd.DataFrame(data)
XOR

x1  x2  y
0   0   0  0
1   0   1  1
2   1   0  1
3   1   1  0

In [32]:
X = XOR.drop("y", axis=1) # axis = 1 >>> dropping across column
X

x1  x2
0   0   0
1   0   1
2   1   0
3   1   1

In [33]:
y = XOR['y']
y.to_frame()

y
0  0
1  1
2  1
3  0

In [34]:
model = Perceptron(eta = 0.5, epochs=50)
model.fit(X,y)

self.weights: [ 1.20207436e-06  1.97416932e-05 -5.41153454e-05]
X_with_bias: 
[[ 0.  0. -1.]
 [ 0.  1. -1.]
 [ 1.  0. -1.]
 [ 1.  1. -1.]]
for epoch: 0
predicted value: 
[1 1 1 1]
error: 
0   -1
1    0
2    0
3   -1
Name: y, dtype: int64
updated weights: 
[-0.4999988  -0.49998026  0.99994588]
#############

for epoch: 1
predicted value: 
[0 0 0 0]
error: 
0    0
1    1
2    1
3    0
Name: y, dtype: int64
updated weights: 
[ 1.20207436e-06  1.97416932e-05 -5.41153454e-05]
#############

for epoch: 2
predicted value: 
[1 1 1 1]
error: 
0   -1
1    0
2    0
3   -1
Name: y, dtype: int64
updated weights: 
[-0.4999988  -0.49998026  0.99994588]
#############

for epoch: 3
predicted value: 
[0 0 0 0]
error: 
0    0
1    1
2    1
3    0
Name: y, dtype: int64
updated weights: 
[ 1.20207436e-06  1.97416932e-05 -5.41153454e-05]
#############

for epoch: 4
predicted value: 
[1 1 1 1]
error: 
0   -1
1    0
2    0
3   -1
Name: y, dtype: int64
updated weights: 
[-0.4999988  -0.49998026  0.99994588]
##

# Conclusion:
Here we can see Perceptron can only classify the linear problem like AND, OR operation because they were linear problem. But in the case of XOR it couldn't classify correctly because it was a non-linear problem. Lets see graphically.

## Analysis with the graph

# Saving and Loading model

In [36]:
import os
import joblib
# saving model
dir_ = "Perceptron_model"
os.makedirs(dir_, exist_ok=True)
filename = os.path.join(dir_, 'AND_model.model')
joblib.dump(model, filename)

['Perceptron_model/AND_model.model']

In [37]:
# load the model from drive
loaded_model = joblib.load(filename)
result = loaded_model.predict(X)
print(result)

[1 1 1 1]
